x == float(input())
a == float(input())
y == float(input())
b == float(input())
print('Один кг шоколадных конфет стоит', a / x, 'рублей')
print('Один кг ирисок стоит', b / y, 'рублей')
print('Шоколадные конфеты дороже ирисок в', x // y, 'раз')
